apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge
  template:
    metadata:
      labels:
        app: edge
        track: stable
    spec:
      containers:
      - name: edge
        image: wangjing0801/industrial-edge:1.2.6
        ports:
        - containerPort: 30972
 
---
apiVersion: v1
kind: Service
metadata:
  name: edge-svc
spec:
  type: NodePort
  selector:
    app: edge
  ports:
  - protocol: TCP
    port: 30972
    targetPort: 30972